// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_UxsyMdOnj1ml0ns4FfxLE8iXG4FBPPc',
    appId: '1:340989841276:web:c5e8a38e515a51486adef9',
    messagingSenderId: '340989841276',
    projectId: 'financy-f0f1a',
    authDomain: 'financy-f0f1a.firebaseapp.com',
    storageBucket: 'financy-f0f1a.firebasestorage.app',
    measurementId: 'G-0EGWW6HCXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6S9T8DrVDbEQ59OCX4ZrwdBdd8DJaIRs',
    appId: '1:340989841276:android:9956fca72f4ab9e16adef9',
    messagingSenderId: '340989841276',
    projectId: 'financy-f0f1a',
    storageBucket: 'financy-f0f1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh9OYHlRqdLf2LjzyhoQz3R9-BqrKLKQc',
    appId: '1:340989841276:ios:2ef4d8b9102ac57a6adef9',
    messagingSenderId: '340989841276',
    projectId: 'financy-f0f1a',
    storageBucket: 'financy-f0f1a.firebasestorage.app',
    iosBundleId: 'dev.sayrix.financy.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh9OYHlRqdLf2LjzyhoQz3R9-BqrKLKQc',
    appId: '1:340989841276:ios:2ef4d8b9102ac57a6adef9',
    messagingSenderId: '340989841276',
    projectId: 'financy-f0f1a',
    storageBucket: 'financy-f0f1a.firebasestorage.app',
    iosBundleId: 'dev.sayrix.financy.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_UxsyMdOnj1ml0ns4FfxLE8iXG4FBPPc',
    appId: '1:340989841276:web:65257224b38427946adef9',
    messagingSenderId: '340989841276',
    projectId: 'financy-f0f1a',
    authDomain: 'financy-f0f1a.firebaseapp.com',
    storageBucket: 'financy-f0f1a.firebasestorage.app',
    measurementId: 'G-MP3EMN92J9',
  );
}
